name: CI

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main, develop ]

jobs:
  engine-desktop:
    name: C++ Engine/Desktop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build clang-tidy
      - name: Build engine
        run: |
          cmake -S engine -B engine/build -G Ninja -DVERITY_ENGINE_BUILD_TESTS=ON
          cmake --build engine/build --config Release
          ctest --test-dir engine/build --output-on-failure
      - name: Run clang-tidy (engine)
        run: |
          clang-tidy engine/src/engine.cpp -- -Iengine/include
      - name: Build desktop stub
        run: |
          cmake -S desktop -B desktop/build -G Ninja
          cmake --build desktop/build --config Release

  backend:
    name: Backend (Python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Lint & Format check
        working-directory: backend
        run: |
          ruff check .
          black --check .
      - name: Tests
        working-directory: backend
        run: pytest -q
      - name: pip-audit
        working-directory: backend
        run: pip-audit

  web:
    name: Web (React/TS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package.json
      - name: Install
        working-directory: web
        run: npm install --no-fund --no-audit
      - name: Lint
        working-directory: web
        run: npm run lint
      - name: Typecheck
        working-directory: web
        run: npm run typecheck
      - name: Tests
        working-directory: web
        run: npm test
      - name: Build
        working-directory: web
        run: npm run build
